services:
    overleaf:
        restart: unless-stopped
        image: sharelatex/sharelatex:5
        container_name: overleaf
        depends_on:
            mongo:
                condition: service_started
            redis:
                condition: service_started
        ports:
            - 9153:80
        links:
            - mongo
            - redis
        volumes:
            - sharelatex_data:/var/lib/overleaf
        networks:
            - overleaf_net
        environment:

            OVERLEAF_APP_NAME: OverLeaf
            OVERLEAF_MONGO_URL: mongodb://mongo/overleaf
            # Same property, unfortunately with different names in
            # different locations
            OVERLEAF_REDIS_HOST: redis
            REDIS_HOST: redis
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'
            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'true'
            # temporary fix for LuaLaTex compiles
            # see https://github.com/overleaf/overleaf/issues/695
            TEXMFVAR: /var/lib/overleaf/tmp/texmf-var


    mongo:
        restart: unless-stopped
        image: bitnami/mongodb:5.0
        container_name: mongo
        environment:
            MONGODB_REPLICA_SET_MODE: primary
            ALLOW_EMPTY_PASSWORD: 'yes'
        expose:
            - 27017
        volumes:
            - mongodb_data:/data/db
        networks:
            - overleaf_net
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: unless-stopped
        image: redis:6.2-alpine
        container_name: redis
        expose:
            - 6379
        volumes:
            - redis_data:/data
        networks:
            - overleaf_net
networks:
  overleaf_net:
volumes:
  redis_data:
  sharelatex_data:
  mongodb_data:

